import express from "express";
import { createServer as createViteServer } from "vite";
import { GoogleGenAI } from "@google/genai";
import dotenv from "dotenv";

dotenv.config();

function generateFallbackSprite(modelType: string, prompt: string): string {
  let iconEmoji = '🏰';
  let bgColor = '#1e293b';
  let borderColor = '#f59e0b';
  
  if (modelType === 'corridor_goblin') { iconEmoji = '👾'; borderColor = '#22c55e'; }
  else if (modelType === 'mining_node') { iconEmoji = '⛏️'; borderColor = '#38bdf8'; }
  else if (modelType === 'shadow_stalker') { iconEmoji = '👻'; borderColor = '#a855f7'; }
  else if (modelType === 'foreman') { iconEmoji = '👑'; borderColor = '#ef4444'; }
  else if (modelType === 'watchtower') { iconEmoji = '🏛️'; borderColor = '#f59e0b'; }

  const svg = `<svg xmlns="http://www.w3.org/2000/svg" width="256" height="256" viewBox="0 0 256 256">
    <defs>
      <linearGradient id="grad" x1="0%" y1="0%" x2="100%" y2="100%">
        <stop offset="0%" stop-color="${bgColor}" />
        <stop offset="100%" stop-color="#0f172a" />
      </linearGradient>
      <filter id="glow">
        <feGaussianBlur stdDeviation="6" result="coloredBlur"/>
        <feMerge>
          <feMergeNode in="coloredBlur"/>
          <feMergeNode in="SourceGraphic"/>
        </feMerge>
      </filter>
    </defs>
    <rect width="256" height="256" rx="32" fill="url(#grad)" stroke="${borderColor}" stroke-width="6"/>
    <polygon points="128,40 220,100 128,160 36,100" fill="${borderColor}" opacity="0.3"/>
    <text x="128" y="130" font-size="72" text-anchor="middle" dominant-baseline="middle" filter="url(#glow)">${iconEmoji}</text>
    <text x="128" y="200" font-size="13" fill="#cbd5e1" font-family="sans-serif" font-weight="bold" text-anchor="middle">${modelType.toUpperCase()}</text>
    <text x="128" y="220" font-size="10" fill="#94a3b8" font-family="sans-serif" text-anchor="middle">AI DelveCraft Sprite</text>
  </svg>`;

  return `data:image/svg+xml;base64,${Buffer.from(svg).toString('base64')}`;
}

async function startServer() {
  const app = express();
  app.use(express.json({ limit: '10mb' }));

  const ai = new GoogleGenAI({
    apiKey: process.env.GEMINI_API_KEY,
    httpOptions: {
      headers: {
        'User-Agent': 'aistudio-build',
      }
    }
  });

  // AI Tile / Model Generation endpoint with robust quota fallback
  app.post("/api/generate-tile-image", async (req, res) => {
    try {
      const { prompt, modelType } = req.body;
      const fullPrompt = `Isometric 2.5D game sprite asset, ${modelType || 'game object'}: ${prompt}, top-down isometric projection, game art sprite, high contrast, clean transparent or neutral background`;

      const response = await ai.models.generateContent({
        model: 'gemini-3.1-flash-lite-image',
        contents: {
          parts: [{ text: fullPrompt }],
        },
        config: {
          imageConfig: {
            aspectRatio: "1:1",
            imageSize: "1K"
          }
        }
      });

      let imageUrl = '';
      for (const part of response.candidates?.[0]?.content?.parts || []) {
        if (part.inlineData) {
          imageUrl = `data:image/png;base64,${part.inlineData.data}`;
        }
      }

      if (!imageUrl) {
        throw new Error("No image generated by Gemini model.");
      }

      res.json({ success: true, imageUrl });
    } catch (err: any) {
      console.warn("AI Generation quota or error encountered. Using procedural high-performance fallback sprite:", err.message);
      const fallbackUrl = generateFallbackSprite(req.body.modelType || 'asset', req.body.prompt || '');
      res.json({ 
        success: true, 
        imageUrl: fallbackUrl,
        fallbackNotice: "Quota limit reached; using high-grade procedural fallback sprite." 
      });
    }
  });

  // Vite middleware for development
  const vite = await createViteServer({
    server: { middlewareMode: true },
    appType: "spa",
  });
  app.use(vite.middlewares);

  const port = Number(process.env.PORT) || 3000;
  app.listen(port, "0.0.0.0", () => {
    console.log(`Server running on http://localhost:${port}`);
  });
}

startServer();
